Web/SampleBookingSystem.Web/Models/Reservation/CreateReservationViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SampleBookingSystem.Common;
using SampleBookingSystem.Common.CustomAttributes;

namespace SampleBookingSystem.Web.Models.Reservation
{
    public class CreateReservationViewModel
    {
        [Required(ErrorMessage = GlobalConstants.MissingRoomIdMessage)]
        [Range(1, 16)]
        public int RoomId { get; set; }

        [Required]
        [ValidCheckinDate(ErrorMessage = GlobalConstants.CheckinDateErrorMessage)]
        [DataType(DataType.Date)]
        public DateTime CheckinDate { get; set; } = DateTime.Now;

        [Required]
        [ValidCheckoutDate(ErrorMessage = GlobalConstants.CheckoutDateErrorMessage)]
        [DataType(DataType.Date)]
        public DateTime CheckoutDate { get; set; } = DateTime.Now;

        public SelectList FreeRoomsList { get; set; }
    }
}

Web/SampleBookingSystem.Web/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SampleBookingSystem.Data.Models;
using SampleBookingSystem.Services.Data.Contracts;
using SampleBookingSystem.Web.Models.Reservation;

namespace SampleBookingSystem.Web.Controllers
{
    [Authorize]
    public class ReservationController : BaseController
    {
        private IReservationsService reservations;
        private IRoomService rooms;

        public ReservationController(IReservationsService reservations, IRoomService rooms)
        {
            this.reservations = reservations;
            this.rooms = rooms;
        }

        [HttpGet]
        public ActionResult BookRooms()
        {
            var freeRooms = this.rooms.GetAllFreeRooms()
                                      .Select(r => r.Id)
                                      .ToList();

            var model = new CreateReservationViewModel()
            {
                FreeRoomsList = new SelectList(freeRooms, "RoomId")
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BookRooms(CreateReservationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newReservation = new Reservation
                {
                    UserId = User.Identity.GetUserId(),
                    RoomId = model.RoomId,
                    CheckinDate = model.CheckinDate,
                    ChechoutDate = model.CheckoutDate
                };

                int newReservationId = reservations.AddReservation(newReservation);

                return Content($"Reservation added: {newReservationId}");
            }

            var freeRooms = this.rooms.GetAllFreeRooms().Select(r => r.Id).ToList();
            model.FreeRoomsList = new SelectList(freeRooms, "RoomId");

            return View(model);
        }
    }
}

Web/SampleBookingSystem.Web/Views/Reservation/BookRooms.cshtml
@model SampleBookingSystem.Web.Models.Reservation.CreateReservationViewModel

@{
    ViewBag.Title = "BookRooms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BookRooms</h2>
@using (@Html.BeginForm("BookRooms", "Reservation", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <fieldset>
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()

        <div class="form-group">
            @Html.Label("Free rooms", new { @class = "col-md-3 control-label" })
            <div class="col col-md-2">
                @Html.DropDownList("RoomId", Model.FreeRoomsList, "Select room", new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CheckinDate, new { @class = "col-md-3 control-label" })
            <div class="col col-md-2">
                @Html.EditorFor(m => m.CheckinDate, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CheckoutDate, new { @class = "col-md-3 control-label" })
            <div class="col col-md-9">
                @Html.EditorFor(m => m.CheckoutDate, new { @class = "form-control" })
            </div>
        </div>

        <input type="submit" value="Save" class="col-md-offset-3 btn btn-success" />
        @Html.ActionLink("Reset", "BookRooms", "Reservation", new { @class = "btn btn-danger" })
    </fieldset>
}